### ISSUE TITLE
我觉得标题就不对

### ISSUE THREAD

**Issue by WeeTom** [freedombird9/code-easy-to-delete#3]
Write code that is easy to delete, not easy to extend.
写容易删除的代码，而不是容易扩展的代码。
如果作者要说的是不容易扩展的代码，会用diffcult to extend. not 对应的是not write code that is

**Comment by freedombird9** [comment]
问了两个美国人，这两种理解都可以，因为作者省略太多了。但我个人也认为作者更多的是指 Don't write code that's easy to extend。看个人理解吧。

**Comment by freedombird9** [comment]
嗯，Don't write code that's easy to extend 确实更符合常识一点。
